name: bacterial-genomics-tutorial
channels:
  - conda-forge
  - bioconda
  - daler
  - defaults
dependencies:
  - samtools
  - bwa
  - fastqc
  - python=3
  - minimap2
  - ragtag
  - abricate
  - mlst
  - spades
  - minimap2
  - mummer
  - mash
  - roary
  - mafft
  - prokka
  - quast
  - sickle-trim
  - porechop
  - pip
  - pip:
      - numpy
      - matplotlib
      - matplotlib-venn
      - biopython
      - dREP
